[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "s3import"
description = "A Salesforce Function that imports documents in AWS S3"
type = "function"
salesforce-api-version = "54.0"